### ISSUE TITLE
v0.8.0 does not work with Embulk v0.9.23

### ISSUE THREAD

**Issue by kamikaseda** [treasure-data/embulk-output-td#114]
h3. Description
embulk-output-td v0.8.0 does not work with Embulk v0.9.23 due to the following error.

```
$ embulk run load.yml
2021-12-01 18:51:15.176 +0900: Embulk v0.9.23
2021-12-01 18:51:16.025 +0900 [WARN] (main): DEPRECATION: JRuby org.jruby.embed.ScriptingContainer is directly injected.
2021-12-01 18:51:18.433 +0900 [INFO] (main): Gem's home and path are set by default: "/Users/user/.embulk/lib/gems"
2021-12-01 18:51:19.310 +0900 [INFO] (main): Started Embulk v0.9.23
2021-12-01 18:51:19.449 +0900 [INFO] (0001:transaction): Loaded plugin embulk-output-td (0.8.0)
2021-12-01 18:51:19.898 +0900 [INFO] (0001:transaction): Listing local files at directory '/Users/kamikaseda/Documents/work/Embulk' filtering filename by prefix 'test'
2021-12-01 18:51:19.899 +0900 [INFO] (0001:transaction): "follow_symlinks" is set false. Note that symbolic links to directories are skipped.
2021-12-01 18:51:19.904 +0900 [INFO] (0001:transaction): Loading files [/Users/kamikaseda/Documents/work/Embulk/test.csv]
2021-12-01 18:51:19.945 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=24 / output tasks 12 = input tasks 1 * 12
org.embulk.exec.PartialExecutionException: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.type.ReferenceType.upgradeFrom(Lcom/fasterxml/jackson/databind/JavaType;Lcom/fasterxml/jackson/databind/JavaType;)Lcom/fasterxml/jackson/databind/type/ReferenceType;
	at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:340)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:566)
	at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:353)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:350)
	at org.embulk.spi.Exec.doWith(Exec.java:22)
	at org.embulk.exec.BulkLoader.run(BulkLoader.java:350)
	at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:242)
	at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:291)
	at org.embulk.EmbulkRunner.run(EmbulkRunner.java:155)
	at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:431)
	at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:90)
	at org.embulk.cli.Main.main(Main.java:64)
	Suppressed: java.lang.NullPointerException
		at org.embulk.exec.BulkLoader.doCleanup(BulkLoader.java:463)
		at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:397)
		at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:394)
		at org.embulk.spi.Exec.doWith(Exec.java:22)
		at org.embulk.exec.BulkLoader.cleanup(BulkLoader.java:394)
		at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:245)
		... 5 more
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.type.ReferenceType.upgradeFrom(Lcom/fasterxml/jackson/databind/JavaType;Lcom/fasterxml/jackson/databind/JavaType;)Lcom/fasterxml/jackson/databind/type/ReferenceType;
	at com.fasterxml.jackson.datatype.jdk8.Jdk8TypeModifier.modifyType(Jdk8TypeModifier.java:40)
	at com.fasterxml.jackson.databind.type.TypeFactory._constructType(TypeFactory.java:525)
	at com.fasterxml.jackson.databind.type.TypeFactory.constructType(TypeFactory.java:474)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3388)
	at org.embulk.util.config.TaskObjectsRetriever.buildTaskBackingObjectsOnlyAvailableInJson(TaskObjectsRetriever.java:167)
	at org.embulk.util.config.TaskObjectsRetriever.buildTaskBackingObjects(TaskObjectsRetriever.java:104)
	at org.embulk.util.config.ConfigTaskDeserializer.deserialize(ConfigTaskDeserializer.java:42)
	at org.embulk.util.config.ConfigTaskDeserializer.deserialize(ConfigTaskDeserializer.java:28)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3708)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2005)
	at org.embulk.util.config.ConfigMapper.map(ConfigMapper.java:80)
	at org.embulk.output.td.TdOutputPlugin.transaction(TdOutputPlugin.java:390)
	at org.embulk.exec.BulkLoader$4$1$1.transaction(BulkLoader.java:521)
	at org.embulk.exec.LocalExecutorPlugin.transaction(LocalExecutorPlugin.java:50)
	at org.embulk.exec.BulkLoader$4$1.run(BulkLoader.java:516)
	at org.embulk.spi.util.Filters$RecursiveControl.transaction(Filters.java:84)
	at org.embulk.spi.util.Filters.transaction(Filters.java:42)
	at org.embulk.exec.BulkLoader$4.run(BulkLoader.java:511)
	at org.embulk.spi.FileInputRunner$RunnerControl$1$1.run(FileInputRunner.java:112)
	at org.embulk.standards.CsvParserPlugin.transaction(CsvParserPlugin.java:237)
	at org.embulk.spi.FileInputRunner$RunnerControl$1.run(FileInputRunner.java:107)
	at org.embulk.spi.util.Decoders$RecursiveControl.transaction(Decoders.java:68)
	at org.embulk.spi.util.Decoders.transaction(Decoders.java:29)
	at org.embulk.spi.FileInputRunner$RunnerControl.run(FileInputRunner.java:105)
	at org.embulk.standards.LocalFileInputPlugin.resume(LocalFileInputPlugin.java:79)
	at org.embulk.standards.LocalFileInputPlugin.transaction(LocalFileInputPlugin.java:72)
	at org.embulk.spi.FileInputRunner.transaction(FileInputRunner.java:62)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:507)
	... 11 more

Error: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.type.ReferenceType.upgradeFrom(Lcom/fasterxml/jackson/databind/JavaType;Lcom/fasterxml/jackson/databind/JavaType;)Lcom/fasterxml/jackson/databind/type/ReferenceType;
```

h3. What I confirmed
I simply reverted embulk-output-td vestion to 0.7.2, then it works fine. Of-course there is no change in yml file.

```
$ embulk run load.yml
2021-12-01 18:55:31.999 +0900: Embulk v0.9.23
2021-12-01 18:55:32.945 +0900 [WARN] (main): DEPRECATION: JRuby org.jruby.embed.ScriptingContainer is directly injected.
2021-12-01 18:55:34.945 +0900 [INFO] (main): Gem's home and path are set by default: "/Users/user/.embulk/lib/gems"
2021-12-01 18:55:35.640 +0900 [INFO] (main): Started Embulk v0.9.23
2021-12-01 18:55:35.757 +0900 [INFO] (0001:transaction): Loaded plugin embulk-output-td (0.7.2)
2021-12-01 18:55:35.816 +0900 [INFO] (0001:transaction): Listing local files at directory '/Users/kamikaseda/Documents/work/Embulk' filtering filename by prefix 'test'
2021-12-01 18:55:35.817 +0900 [INFO] (0001:transaction): "follow_symlinks" is set false. Note that symbolic links to directories are skipped.
2021-12-01 18:55:35.821 +0900 [INFO] (0001:transaction): Loading files [/Users/user/Documents/work/Embulk/test.csv]
2021-12-01 18:55:35.852 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=24 / output tasks 12 = input tasks 1 * 12
2021-12-01 18:55:35.884 +0900 [INFO] (0001:transaction): td-client version: 0.9.5
2021-12-01 18:55:35.889 +0900 [INFO] (0001:transaction): Reading configuration file: /Users/user/.td/td.conf
2021-12-01 18:55:37.190 +0900 [WARN] (0001:transaction): [TARGET_ALREADY_EXISTS] [409:Conflict] API request to /v3/table/create/db_name/tab_name/log has failed: ["Name has already been taken"]
2021-12-01 18:55:37.638 +0900 [INFO] (0001:transaction): Duplicating timestamp:timestamp column to 'time' column as seconds for the data partitioning
2021-12-01 18:55:37.638 +0900 [INFO] (0001:transaction): Create bulk_import session embulk_20211201_095535_641000000_9c75e977_5c21_4a8f_ab11_cf08206b67b7
2021-12-01 18:55:38.261 +0900 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2021-12-01 18:55:38.381 +0900 [INFO] (0017:task-0000): {uploading: {rows: 6, size: 212 bytes (compressed)}}
2021-12-01 18:55:39.387 +0900 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
2021-12-01 18:55:40.121 +0900 [INFO] (0001:transaction): Performing bulk import session 'embulk_20211201_095535_641000000_9c75e977_5c21_4a8f_ab11_cf08206b67b7'
2021-12-01 18:56:09.286 +0900 [INFO] (0001:transaction):     job id: 1220797762
2021-12-01 18:56:09.999 +0900 [INFO] (0001:transaction): Committing bulk import session 'embulk_20211201_095535_641000000_9c75e977_5c21_4a8f_ab11_cf08206b67b7'
2021-12-01 18:56:09.999 +0900 [INFO] (0001:transaction):     valid records: 6
2021-12-01 18:56:09.999 +0900 [INFO] (0001:transaction):     error records: 0
2021-12-01 18:56:09.999 +0900 [INFO] (0001:transaction):     valid parts: 1
2021-12-01 18:56:09.999 +0900 [INFO] (0001:transaction):     error parts: 0
2021-12-01 18:56:09.999 +0900 [INFO] (0001:transaction):     new columns:
2021-12-01 18:56:09.999 +0900 [INFO] (0001:transaction):       - id: long
2021-12-01 18:56:09.999 +0900 [INFO] (0001:transaction):       - name: string
2021-12-01 18:56:10.000 +0900 [INFO] (0001:transaction):       - timestamp: string
2021-12-01 18:56:14.164 +0900 [INFO] (0001:transaction): Deleting bulk import session 'embulk_20211201_095535_641000000_9c75e977_5c21_4a8f_ab11_cf08206b67b7'
2021-12-01 18:56:15.092 +0900 [INFO] (main): Committed.
2021-12-01 18:56:15.092 +0900 [INFO] (main): Next config diff: {"in":{"last_path":"/Users/user/Documents/work/Embulk/test.csv"},"out":{"last_session":"embulk_20211201_095535_641000000_9c75e977_5c21_4a8f_ab11_cf08206b67b7"}}
```

**Comment by dmikurube** [comment]
@kamikaseda Ah, thanks! Yes, we are aware of that, but it turned out that the "embulk-output-td's catch up with the new Embulk v0.10.*'s SPI manner" **cannot** work with Embulk v0.9.23 unavoidably.

To deal with that issue, we released Embulk v0.9.24 as a kind of backport. (Try `embulk selfupdate 0.9.24`. `embulk-latest.jar` does not point v0.9.24 yet until we have a certain amount of confirmation. It'll be updated in 1-2 weeks.)

We'll have to update README of this plugin.

**Comment by kamikaseda** [comment]
@dmikurube I see. I got it!

**Comment by dmikurube** [comment]
Updated `README.md`. https://github.com/treasure-data/embulk-output-td/blob/c3e147e859ef9279e2450b29fb97af82e4a7a666/README.md
